# Generated by Django 4.2.6 on 2023-12-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('DELIVERED', 'delivered')], max_length=255),
        ),
    ]
