# Generated by Django 4.2.6 on 2023-12-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payments_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payments',
            new_name='payment',
        ),
    ]
